"""init

Revision ID: 3bc608c927a8
Revises:
Create Date: 2026-06-16 17:14:02.595379

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "3bc608c927a8"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "given_stars",
        sa.Column("user_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("given_star_amount", mysql.INTEGER(unsigned=True), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "monthly_action_powers",
        sa.Column("user_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("action_power", mysql.INTEGER(unsigned=True), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "monthly_powers",
        sa.Column("user_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("text_power", mysql.INTEGER(unsigned=True), nullable=False),
        sa.Column("voice_power", mysql.INTEGER(unsigned=True), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "role_panel_categories",
        sa.Column("category_id", mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=True),
        sa.Column("display_order", mysql.INTEGER(unsigned=True), nullable=False),
        sa.Column("requires_boost", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("category_id"),
    )
    op.create_table(
        "star_grades",
        sa.Column("user_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("prestige", mysql.TINYINT(unsigned=True), nullable=False),
        sa.Column("grade", mysql.TINYINT(unsigned=True), nullable=False),
        sa.Column("shard", mysql.INTEGER(unsigned=True), nullable=False),
        sa.Column("text_shard", mysql.INTEGER(unsigned=True), nullable=False),
        sa.Column("voice_shard", mysql.INTEGER(unsigned=True), nullable=False),
        sa.Column("bonus_shard", mysql.INTEGER(unsigned=True), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "starred_messages",
        sa.Column("starred_message_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("starboard_message_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("star_amount", mysql.INTEGER(unsigned=True), nullable=False),
        sa.Column("user_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("starred_message_channel_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("starred_message_id"),
    )
    op.create_table(
        "user_birthdays",
        sa.Column("user_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "user_roles",
        sa.Column("user_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("role_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("user_id", "role_id"),
    )
    op.create_table(
        "voice_xp_limits",
        sa.Column("user_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("voice_shard", mysql.INTEGER(unsigned=True), nullable=False),
        sa.Column("bonus_shard", mysql.INTEGER(unsigned=True), nullable=False),
        sa.Column("voice_power", mysql.INTEGER(unsigned=True), nullable=False),
        sa.Column("half_notify", sa.Boolean(), nullable=False),
        sa.Column("full_notify", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "xp_boosts",
        sa.Column("role_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("boost_amount", mysql.INTEGER(unsigned=True), nullable=False),
        sa.Column("boost_end_time", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("role_id"),
    )
    op.create_table(
        "role_panel_roles",
        sa.Column("category_id", mysql.INTEGER(unsigned=True), nullable=False),
        sa.Column("role_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("display_order", mysql.INTEGER(unsigned=True), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["category_id"], ["role_panel_categories.category_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("category_id", "role_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("role_panel_roles")
    op.drop_table("xp_boosts")
    op.drop_table("voice_xp_limits")
    op.drop_table("user_roles")
    op.drop_table("user_birthdays")
    op.drop_table("starred_messages")
    op.drop_table("star_grades")
    op.drop_table("role_panel_categories")
    op.drop_table("monthly_powers")
    op.drop_table("monthly_action_powers")
    op.drop_table("given_stars")
    # ### end Alembic commands ###
