"""add database indexes

Revision ID: 7ba51941f7cc
Revises: 273b6467e5ff
Create Date: 2026-06-22 17:21:24.127800

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7ba51941f7cc"
down_revision: str | Sequence[str] | None = "273b6467e5ff"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("idx_given_stars_given_star_amount", "given_stars", ["given_star_amount"], unique=False)
    op.create_index(
        "idx_role_panel_categories_display_order", "role_panel_categories", ["display_order"], unique=False
    )
    op.create_index(
        "idx_role_panel_roles_category_order",
        "role_panel_roles",
        ["category_id", "display_order", "role_id"],
        unique=False,
    )
    op.create_index("idx_star_grades_ranking", "star_grades", ["prestige", "grade", "shard"], unique=False)
    op.create_index("idx_starred_messages_star_amount", "starred_messages", ["star_amount"], unique=False)
    op.create_index("idx_starred_messages_user_id", "starred_messages", ["user_id"], unique=False)
    op.create_index("idx_user_birthdays_date", "user_birthdays", ["date"], unique=False)
    op.create_index("idx_xp_boosts_boost_end_time", "xp_boosts", ["boost_end_time"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_xp_boosts_boost_end_time", table_name="xp_boosts")
    op.drop_index("idx_user_birthdays_date", table_name="user_birthdays")
    op.drop_index("idx_starred_messages_user_id", table_name="starred_messages")
    op.drop_index("idx_starred_messages_star_amount", table_name="starred_messages")
    op.drop_index("idx_star_grades_ranking", table_name="star_grades")
    op.drop_index("idx_role_panel_roles_category_order", table_name="role_panel_roles")
    op.drop_index("idx_role_panel_categories_display_order", table_name="role_panel_categories")
    op.drop_index("idx_given_stars_given_star_amount", table_name="given_stars")
    # ### end Alembic commands ###
